### ISSUE TITLE
Chained exceptions

### ISSUE THREAD

**Issue by a-martynovich** [MindscapeHQ/raygun4py#10]
Dear developers,

Raygun REST API supports chained exceptions using nested innerError. Would be very nice to have Python3 chained exception support in raygun4py. 

Thanks

**Comment by CmdrKeen** [comment]
Hi,

I believe @fundead is looking into this at present -- perhaps he can share what's involved with adding support?

**Comment by Kentzo** [comment]
:+1: 

We really need it as well.

**Comment by Kentzo** [comment]
Needless to say that we're commercial users…

**Comment by fundead** [comment]
Hi all,

We're involved in a large pass over the providers at the moment, which will include getting support for chained exceptions into this provider. I will link this issue here when the feature is available, which should be in the very near term.

Regards,

Callum Gavin
Mindscape Limited

**Comment by fundead** [comment]
closed in #12
