### ISSUE TITLE
WSGI middleware exception on close() looks broken.

### ISSUE THREAD

**Issue by GrahamDumpleton** [MindscapeHQ/raygun4py#22]
Just on visual inspection the code at:

* https://github.com/MindscapeHQ/raygun4py/blob/master/python2/raygun4py/middleware/wsgi.py#L35

looks broken.

```
        finally:
            if chunk and hasattr(chunk, 'close') and callable(chunk.close):
                try:
                    chunk.close()
                except Exception as e:
                    request = build_request(environ)
                    self.send_exception(exception=e, request=request)
```

Shouldn't that be calling ``self.sender.send_exception()``?

You also aren't reraising the exception.

Technically you also shouldn't be checking to see if ``close()`` is callable and instead should just call it. By checking to see if it is callable you are hiding to a higher layer that the ``close()`` method wasn't callable, which is actually an error in itself as far as the code satisfying the WSGI specification.

**Comment by fundead** [comment]
Good spotting - indeed it should, I will put a fix in for this in the next release.

The implementation was based off of others but I'll have a dig at the spec and make sure we're matching it with regards to `close()`.

**Comment by GrahamDumpleton** [comment]
The implementation of ``close()`` is an area which is too often done wrongly and why I specifically look for it. :-)

I have already found multiple ``close()`` issues in uWSGI, Django development server, wsgiref and other WSGI servers. Also seen issues in Sentry and other WSGI middleware.

You can see what I have said about it in:

* http://blog.dscpl.com.au/2012/10/obligations-for-calling-close-on.html

**Comment by fundead** [comment]
Just an update on this one, the fix has been merged as per your advice for the best-practice implementation at the bottom of the above blog post. Would like to that you for finding and raising this issue.

Regards,

Callum Gavin
Raygun Limited
