### ISSUE TITLE
Errors should be logged instead of printed to stderr

### ISSUE THREAD

**Issue by Osmose** [MindscapeHQ/raygun4py#28]
There's a few places (such as [raygunprovider.py](https://github.com/MindscapeHQ/raygun4py/blob/2c28a2f349d2b52998efd778027c98803372faba/python2/raygun4py/raygunprovider.py#L21)) that print error messages to stderr. It'd be better to log these as errors using standard Python logging so apps can filter them and log them to the correct place.

(In particular I'm hitting these messages while running tests in Django locally, where messages about not logging to Raygun don't matter.)

It'd also help categorize the errors; the message linked above would be better-suited as a warning rather than an error, since execution continues even if no API key is set.

I hope to submit a PR to fix this within the next few days when I can get to it. :D

**Comment by fundead** [comment]
Good point, you're quite right as using the logger would be a much better experience. The change to `warning` also sounds reasonable. If you do manage to get a PR submitted I'll queue it up for the next release which should be in the near term.

**Comment by abloomston** [comment]
:+1: for this getting fixed.

**Comment by fundead** [comment]
Just an update on this one, this is still in the pipeline and I had hoped to get on to a release of the Python provider before the end of the year, but due to other pressing work this has been shifted to a sprint in the new year.

Regards,

Callum Gavin
Raygun Limited
