### ISSUE TITLE
No middleware integration in Python3

### ISSUE THREAD

**Issue by SchubmannM** [MindscapeHQ/raygun4py#30]
Any ideas on if/when the middleware functionality will be available on python3?

**Comment by fundead** [comment]
We can implement this for you on a per-framework basis. Which web framework are you using? This provider is queued up for a new release in the coming weeks so additional middleware for frameworks that support Python 3 can be added in that release.

Regards,

Callum Gavin
Raygun Limited

**Comment by SchubmannM** [comment]
Hi Callum,
I’m using the Django framework, would be awesome if it would be implemented ☺

Max

**Comment by fundead** [comment]
Cheers for that, I've got this noted down to implement for you soon. Will reply here when it's good to go.

**Comment by mpachas** [comment]
I'm interested on this, too. Thanks

**Comment by Koed00** [comment]
How's this coming along?

**Comment by fundead** [comment]
This feature is queued up for our next sprint and should be available in the near term. I will get back to you when this is ready to go.

**Comment by RogerNoble** [comment]
Hi, Probably a bit late for 3.1.0, but I'd be interested in Flask support.

**Comment by fundead** [comment]
Hi Roger and others,

Fortunately I've had time to port the Flask middleware over to Python 3 for v3.1.0. This is being QA'd now so the release should be out soon will full support for Django, Flask and generic WSGI with PY3.

**Comment by RogerNoble** [comment]
Fantastic thanks!
