### ISSUE TITLE
Disable transmitting local/global variables by default

### ISSUE THREAD

**Issue by mausch** [MindscapeHQ/raygun4py#31]
I was just integrating Raygun to a Flask API and trasmitting local/global variables caused a stackoverflow exception which took me quite some time to understand and fix.

The original error was a Mongo connection that failed because it was missing the connection parameters. When raygun4py tried to get local/global variables it re-triggered the connection initialization for some reason, which in turn caused the exception to be re-raised, etc.

I think these options should be disabled by default. Sending local/global variables automatically is of limited usefulness in real applications anyway. And as the Python Zen says "Explicit is better than implicit.", i.e. in this case this should be opt-in.

**Comment by fundead** [comment]
Hi,

Thanks for the feedback here, this is a valuable failure state to tighten up. Our research indicates that on setup very few people read the documentation and thus are likely to miss what was designed to be quite a unique and helpful feature for debugging if it's buried as an option - users are likely to assume the feature doesn't exist. In fact transmission of local/global variables does subscribe to that explicit over implicit philosophy in that the state of the world at the time of the exception becomes viewable in the Raygun dashboard (which is the experience we're aiming for).

As such the provider will keep defaulting it to true, but we'll prioritize adding guards for this condition to ensure that the provider is rock solid and no loops can prevent the sending or other error handling logic from taking place. This provider is scheduled for a release in the near term so fixes for this issue will make it in then.

Regards,

Callum Gavin
Raygun Limited

**Comment by mausch** [comment]
It was precisely due to not reading the whole documentation that I stumbled for a while trying to look for the cause of my issue, until I read in the code that it was grabbing local/global variables. So the same argument goes both ways there too.
