### ISSUE TITLE
transmit_global_variables is broken

### ISSUE THREAD

**Issue by donspaulding** [MindscapeHQ/raygun4py#39]
The transmit_global_variables should transmit globals respective to the module of the bottom frame of the traceback (e.g. `frame.f_globals` much like `frame.f_locals` is used for local vars).  Here's the code in question:

https://github.com/MindscapeHQ/raygun4py/blob/master/python2/raygun4py/raygunmsgs.py#L121

What this does is transmit the globals of the raygunmsgs.py module, which are almost certainly completely unrelated to the actual error being logged, unless I'm missing something?

**Comment by fundead** [comment]
Thanks for reporting this one, at a review looks like you're correct. I'll investigate this one shortly and look at getting a fix out in the near future.

Regards,

Callum Gavin
Raygun Limited
