### ISSUE TITLE
Accessing directly optional request argument in WSGI middleware

### ISSUE THREAD

**Issue by gzlatkov** [MindscapeHQ/raygun4py#46]
`QUERY_STRING` is an [optional](https://wsgi.readthedocs.io/en/latest/definitions.html)  argument for `environ`, hence should probably be accessed using `get`. Moreover, I think exceptions should not be just `pass`-ed. Currently, if `QUERY_STRING` is absent, `KeyError` will result in `request` be equal to `{}` which will throw another exception when we try to access `headers`.

Valid for both `python2` and `python3`

`python2/raygun4py/middleware/wsgi.py`:

```
try:
    request = {
        'httpMethod': environ['REQUEST_METHOD'],
        'url': environ['PATH_INFO'],
        'ipAddress': environ['REMOTE_ADDR'],
        'hostName': environ['HTTP_HOST'].replace(' ', ''),
        'queryString': environ['QUERY_STRING'],
        'headers': {},
        'form': {},
        'rawData': {}
    }
except Exception:
    pass

for key, value in environ.items():
    if key.startswith('HTTP_'):
       request['headers'][key] = value
```

**Comment by fundead** [comment]
Thanks for your feedback here, looks reasonable. We'll be integrating it in the next release which should be in the near term.

Regards,

Callum Gavin
Raygun Limited
