### ISSUE TITLE
Pypi build version outdated

### ISSUE THREAD

**Issue by BuckinghamIO** [MindscapeHQ/raygun4py#66]
https://pypi.python.org/pypi/raygun4py

Is over 6 months out of date, during this time there have been various fixes and PR including support for Django 1.10 middleware which is fairly vital.

Can a new version be published to Pypi?

**Comment by jscottnz** [comment]
Hi there @BuckinghamIO 

I've tested and merged your PR. The package has been released as version 3.1.6 
Please check that every thing is working as expected and get back to me if you need any thing.

Thanks again for you contributions. I'll will keep an eye on this project for future updates
