### ISSUE TITLE
Add support for wildcard matching of environment variable blacklist

### ISSUE THREAD

**Issue by brock** [MindscapeHQ/raygun4py#88]
Related to #85, but a different functionality...

It would be nice to be able to provide wildcards around certain terms that you'd like to omit from environment variables. For example, right now our config contains a list of known ENV vars, but as more are added, they get sent through.

It would be nice to be able to specify wildcards like the following:

```
FILTERED_KEYS = [
  'AWS_*',
  '*PASSWORD*',
  '*KEY*'
]
```

**Comment by UberMouse** [comment]
Good idea @brock. I've rolled this change into #87

**Comment by UberMouse** [comment]
You can now use a `FILTERED_KEYS` option like your example in the newly released v4.3.0 @brock
