### ISSUE TITLE
Crashed on logging error from a POST in Django

### ISSUE THREAD

**Issue by gwithers** [MindscapeHQ/raygun4py#93]
I was testing the provider and forced an exception handling a POST using Django and Django REST Framework and it triggered the exception masked behind a fault:

You cannot access body after reading from request's data stream

Going into the code, this appears as "request.body" is being accessed.  I fixed locally for test purposes favoring request.data or by just removing the data in favor of the fallback when request doesn't respond to body.

**Comment by pkimber** [comment]
Hello, thank you for sharing this.  I have the same issue, but not sure how to resolve it.
